ros__parameters:
  children:
    names:
    - name: a
    - name: b
    - name: c
    amount: 3
  spots:
    - spot:
        label: corner1
        coordinates:
          translation:
            x: -0.797222
            y: -1.18766
            z: 0.0000568798
          rotation:
            x: 0.000976602
            y: -0.0022919
            z: 0.999974
            w: -0.00679845

    - spot:
        label: corner2
        coordinates:
          translation:
            x: 0.741123
            y: -0.0641682
            z: -0.0000171531
          rotation:
            x: -0.000113579
            y: -0.000587904
            z: 0.999924
            w: 0.0123042

    - spot:
        label: corner3
        coordinates:
          translation:
            x: 0.118575
            y: -0.0710173
            z: -0.000652048
          rotation:
            x: -0.00595093
            y: -0.000168564
            z: 0.999964
            w: -0.00599888

